### ISSUE TITLE
Tatooine Dune Sea/Sand People Territory/Eastern Dune Sea - Sand People disguise bugs

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#6]
When jumping to the Ebon Hawk while wearing the Sand People disguise, it is unequipped (equip clothing instead).

**Comment by DarthParametric** [comment]
Additionally, when moving to different modules while wearing the Sand People disguise, it no longer works at the enclave.

**Comment by Mako88** [comment]
Some useful information regarding this can probably be found here: https://deadlystream.com/topic/6792-kotor-sand-people-enclave-bug/

If Salk has indeed fixed the issues, maybe we can his fixes for inclusion?

**Comment by DarthParametric** [comment]
Someone needs to contact Salk about the current status of the his fix and its potential inclusion in K1CP. Since you were already involved in the thread, do you want to tackle this @JCarter426 ?

**Comment by JCarter426** [comment]
Mm, I don't know if there is anything that could be used but I'll ask.

I do know I discovered an assortment of other related bugs that I wouldn't even know how to begin fixing because none of the scripts would decompile.

**Comment by JCarter426** [comment]
I've fixed everything here and then some. There's one bug I've encountered that I haven't been able to fix, so I'm going to split that off into its own issue.

**Comment by DarthParametric** [comment]
> I'm going to split that off into its own issue
Issue #21

**Comment by DarthParametric** [comment]
This is still not resolved. Entering the Sand People Territory for the first time with a party of Player (disguised), Mission (disguised), HK, the Sand People are hostile. Also happens when swapping out HK for Bastila (disguised). The disguises are equipped in the Dune Sea before transitioning. It seems like if you transition first and _then_ equip the disguises once in the Sand People Territory module, it's ok.

**Comment by JCarter426** [comment]
Closing this again because it _should_ be fixed. You've been playing from the build that had some missing info in changes.ini, if I remember correctly. It was working for both Sniggles and me last weekend.

**Comment by JCarter426** [comment]
Or maybe not. We'll see.

**Comment by JCarter426** [comment]
I tested again and still encounter no problems. @DarthParametric , can you confirm if it works with these hotfix scripts?
[Sand People hotfix 9-29-2019.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3667631/Sand.People.hotfix.9-29-2019.zip)

It's possible there's something wrong with the changes.ini setup that I'm just not seeing.

**Comment by DarthParametric** [comment]
So loading a save in the Dune Sea, I stripped naked, gave it 30 seconds or so to let the Heartbeat tick, equipped the disguise and transited to the Sand People Enclave. With the existing scripts, I get a hostile spawn of Sand People almost straight away, and all the pre-existing Sand People are hostile. Repeating the routine with your attached scripts works as expected - Sand People are neutral. However, I noted that loading from a save in the Dune Sea with the disguises already equipped, I got the hostile response again, so maybe that particular edge case needs a specific check via `if (GetLoadFromSaveGame())`.

**Comment by JCarter426** [comment]
Hmm, could you get video of it? I'm trying to replicate it but they're still neutral and I might not be following the procedure correctly.

**Comment by DarthParametric** [comment]
https://youtu.be/fTn0_WH8MPQ

**Comment by JCarter426** [comment]
Oh, those! Yeah, those are triggered separately from the other disguise stuff and are still unresolved.

**Comment by DarthParametric** [comment]
It should be noted that the resident Sand People are also hostile, as shown at the end. And when using your fixed scripts, I didn't get any of the random spawns (although I'd probably have to go back and run around for 10 mins to make sure it wasn't just luck).

**Comment by JCarter426** [comment]
I'd expect that's due to their AI detecting hostility or some such. I definitely still have them neutral when I don't trigger those random encounters.

Those random encounters are definitely something that should be fixed, but I just keep forgetting about them. And then I was going crazy over the part that is fixed thinking you meant that and not the part I had forgotten about all along.

**Comment by DarthParametric** [comment]
That's the thing though. Whatever it is you did in the above scripts, when I follow the same procedure as in the video with those in the Override I don't get any of those random spawns. I just tested it again and did a bunch of laps of the Sand People Territory and none spawned. And all the residents were neutral, of course.

**Comment by JCarter426** [comment]
I didn't think I'd done anything to fix those. I thought it was reported that they still fired even with the disguise fixes, but maybe they were checking the faction placeable after all.

So are all the problems in the Sand People Territory resolved with the hotfix?

**Comment by DarthParametric** [comment]
Well there's still the issue of having to equip and unequip on a reload. Your fixed version still gives the same result in that scenario. If I keep the disguises on, even waiting 30s or so for the Heartbeat to tick, as soon as I transit to the Sand People Territory I get the same results as in the video.

**Comment by JCarter426** [comment]
Ah, I see. I don't know why, but I'm still not getting those random encounters while disguised. I've tried loading from a save with disguises equipped in both modules, equipping them in the Dune Sea and transiting to the Sand People territory before the heartbeat could kick in, and unequipping/reequipping before transiting. They all resulted in no random encounters and neutral Sand People. Of course I do get the encounters as soon as I unequip a disguise.

**Comment by DarthParametric** [comment]
In the most recent build, I haven't encountered any problems. Unlike last time, I can load an already disguised save in the Dune Sea and transition to the Sand People Territory with no hostility problems. I also noticed there was a filename error in the ini that caused the wrong heartbeat script to be injected into the Eastern Dune Sea module, which I have since fixed.  I think we can call this closed for now. Finally.

**Comment by DarthParametric** [comment]
1.10.0 beta testing observations:

- [ ] Encountered the same issue as before when entering the Sand People Territory with a party of Mission and HK, with both Mission and the PC wearing the disguise. The first time the random spawns triggered and the ambient Sand People were hostile. On subsequent attempts I could not reproduce the behaviour.
- [ ] After peacefully resolving the quest inside the Sand People Enclave, travelling to the Eastern Dune Sea and talking to Komad he remarked that I was wearing the Sand People robes. Checked the global `tat_TuskenSuit` and it was indeed set true despite none of the party wearing disguises.
